on:
  push:
    branches:
      - main

jobs:
  RunTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pytest pytest-spec pytest-describe coverage pytest-mock

      - name: run brute
        run: |
          pytest --spec test_brute.py
          
      - name: test christmas
        run: pytest --spec test_christmas_list.py

      - name: coverage
        run: |
          coverage run -m pytest
          coverage report -m

